### PR TITLE
Added CMakeLists.txt file for building the project

### PR DESCRIPTION
**Pull request by yangosoft**
Simple CMakeLists file to create the target

### CODE REVIEW

**Comment by smellymoo** [comment]
did you get it to build a .exe successfully?

**Comment by yangosoft** [comment]
> did you get it to build a .exe successfully?

No, I don't use Windows but I'll try this week.

By the way, nice program ;)

**Comment by smellymoo** [comment]
thanks! been a lot of work, glad you can help :)

wish I had the time to re-implement the editor that I made before. But at least it is finally alpha! and supporting SML3 too.

**Comment by smellymoo** [comment]
added you as a collaborator, but don't make any changes without a pull request for me to check it through :).

**Comment by yangosoft** [comment]
Great! I will submit you a few PRs.

Best regards,
Yango

**Comment by yangosoft** [comment]
@smellymoo approve this PR to add the CMakeLists and later on we can provide the github action to build it

**Comment by smellymoo** [comment]
I'll review shortly :)

**Comment by smellymoo** [comment]
I can't accept it as it has 2-3 different features in one pull request. 

for example it is changing the cast syntax, and renaming parameters, when it should only change the build system. So adding cmake and maybe git actions would be one pull request.

**Comment by smellymoo** [comment]
I have taken your CMAKE and tweaked it, so I will close this :).

**Pull request closed without merging**
